language: java
jdk:
  - openjdk8
services:
  - docker
env:
  global:
    - DOCKER_IMAGE_FULL_NAME="navikt/eessideploytest:$TRAVIS_COMMIT"
script:
  - #mvn package
  - #docker build -t "$DOCKER_IMAGE_FULL_NAME" .
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master

