language: java
jdk:
  - openjdk8
services:
  - docker
env:
  global:
    - DOCKER_IMAGE_FULL_NAME="navikt/eessideploytest:$TRAVIS_COMMIT"
script:
  - mvn package
  - docker build -t "$DOCKER_IMAGE_FULL_NAME" .
deploy:
  provider: script
  script:
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push "$DOCKER_IMAGE_FULL_NAME"
    - curl -X POST -d@payload.json -H "Accept: application/vnd.github.ant-man-preview+json" -u "$GIT_USERNAME":"$GIT_TOKEN" https://api.github.com/repos/navikt/deploytest/deployments
    
  on:
    branch: master

