language: java
jdk:
  - openjdk8
services:
  - docker
env:
  global:
    - DOCKER_IMAGE_FULL_NAME="navikt/eessideploytest:$TRAVIS_COMMIT"
script:
  - mvn package
  - docker build -t "$DOCKER_IMAGE_FULL_NAME" .
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: master

