apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nais-deploytest
  namespace: default
  labels:
    team: eessibasis
spec:
  image: navikt/eessideploytest:1.1
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://eessideploytest.dev-fss.nais.io"        
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
