version: 2
jobs:
  build:

    working_directory: ~/deploytest

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - run:
          environment:
            DOCKER_IMAGE_FULL_NAME:"navikt/eessideploytest:1.2"
          command: |
            mvn package
            docker build -t "$DOCKER_IMAGE_FULL_NAME" .

      - deploy:
          command: |
            echo "Starting deploy"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push "$DOCKER_IMAGE_FULL_NAME"
              curl -X POST -d@payload.json -H "Accept: application/vnd.github.ant-man-preview+json" -u "$GIT_USERNAME":"$GIT_TOKEN" https://api.github.com/repos/navikt/deploytest/deployments
            fi
