version: 2.0
jobs:
  build:
    environment:
      DOCKER_IMAGE_FULL_NAME: "navikt/eessideploytest:1.2"
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/deploytest
    steps:
      - checkout
      - run:
          name: Build docker image and deploy
          command: |
            mvn package
            docker build -t "$DOCKER_IMAGE_FULL_NAME" .
            echo "Starting deploy $DOCKER_IMAGE_FULL_NAME"
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_IMAGE_FULL_NAME"
            curl -X POST -d@payload.json -H "Accept: application/vnd.github.ant-man-preview+json" -u "$GIT_USERNAME":"$GIT_TOKEN" https://api.github.com/repos/navikt/deploytest/deployments
